/*

Vamos fortalecer e aplicar os conhecimentos, além de aprender truques e dicas para resolver os desafios e avançar para o próximo nível
*/


//-----------------------------------------------------------------

/* ### Transformar notas escolares

Crie um algoritmo que transforme as notas do sitema numerico para sistema de notas em caracteres tipo A B C

* de 90 para cima   -   A
* entre 80 - 89     -   B
* entre 70 - 79     -   C
* entre 60 - 69     -   D
* menor que 60      -   F
*/


